apiVersion: v1
kind: Namespace
metadata:
  name: hatch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-example
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-service
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-example
subjects:
  - kind: ServiceAccount
    name: operator-service
    namespace: default
roleRef:
  kind: ClusterRole
  name: operator-example
  apiGroup: rbac.authorization.k8s.io
---  
apiVersion: v1
kind: Pod
metadata:
  name: hatch
spec:
  serviceAccountName: operator-service
  containers:
    - name: custom-operator
      image: hatch:latest
      imagePullPolicy: Never
